### ISSUE TITLE
Setting up Color Palette

### ISSUE THREAD

**Issue by zlrkw11** [UoaWDCC/ausa#32]
- getting to know about what colors we need for the website

example:
```css
:root {
  --color-primary: #1E40AF;
  --color-secondary: #F59E0B;
  --color-neutral-100: #F5F5F5;
}

body {
  background-color: var(--color-neutral-100);
}
```
- naming conventions to keep in mind
these are good:

> primary, secondary, accent, background, surface, error, info, success, warning

not those:

> red, blue, gray

- with **dark mode**
```css
:root {
  --color-background: #ffffff;
  --color-text: #000000;
}

.dark {
  --color-background: #111827;
  --color-text: #ffffff;
}
```
